version: 0.1
environment_variables:
    plaintext:
        S3_BUCKET: "zobair-bucket-angularui-demo"
        BUILD_ENV: "prod"
        BUILD_SRC_FOLDER: "dist/Demo2"
        S3_TARGET: "zobair-bucket-angularui-demo"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
    post_build:
         commands:
            - aws s3 cp ${BUILD_SRC_FOLDER} s3://${S3_TARGET} --recursive
            - echo Build completed on `date`
artifacts:
    files: 
        - '**/*'
    base-directory: 'dist'
    discard-paths: yes